### ISSUE TITLE
Add Favicons and Webapp Meta

### ISSUE THREAD

**Issue by tylensthilaire** [tylensthilaire/portfolio#2]
Use https://realfavicongenerator.net to generate everything
Note: Touch Bar icon no longer required

- [x] Each page displays a favicon
```html
<!-- Favicons -->
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
```

- [x] Apple devices display icons and app name
```html
<!-- Apple Touch Icon  -->
<link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180">

<!-- To run web application in full-screen -->
<meta name="apple-mobile-web-app-capable" content="yes">

<!-- Status Bar Style (see Supported Meta Tags below for available values) -->
<!-- Must have previous tag set, options are black, white, translucent-black -->
<meta name="apple-mobile-web-app-status-bar-style" content="translucent-black">

<!-- Name app on home screen -->
<meta name="apple-mobile-web-app-title" content="AppTitle">
```

- [x] Windows devices display icons and app name
```html
<!-- Microsoft Tiles -->
<meta name="application-name" content="Name">
<meta name="msapplication-config" content="browserconfig.xml" />
<meta name="msapplication-TileColor" content="#da532c">
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
        <tile>
            <square150x150logo src="/mstile-150x150.png"/>
            <TileColor>#da532c</TileColor>
        </tile>
    </msapplication>
</browserconfig>
```

- [x] Android theme color
```html
<!-- Android theme color -->
<meta name="theme-color" content="#da532c">
```

- [x] Include a web app manifest
* Creates a splashscreen for Chrome 47+
```html
<link rel="manifest" href="manifest.json">
```
```json
{
    "name": "App Name",
    "short_name": "App Name",
    "icons": [
        {
            "src": "/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "theme_color": "#ffffff",
    "background_color": "#ffffff",
    "display": "standalone"
}
```
