### ISSUE TITLE
Social Meta

### ISSUE THREAD

**Issue by tylensthilaire** [tylensthilaire/portfolio#5]
- [x] Open Graph meta exists on base template
- [x] Object type, image, site name and locale are set globally
- [x] Object type and image can be overridden for each page 

```html
<meta property="og:type" content="website">
<meta property="og:url" content="https://example.com/page.html">
<meta property="og:title" content="Content Title">
<meta property="og:image" content="https://example.com/image.jpg">
<meta property="og:description" content="Description Here">
<meta property="og:site_name" content="Site Name">
<meta property="og:locale" content="en_GB">
```
- [x] Twitter card meta exists on base template
- [x] Card type, site, creator, image and alt are set globally
- [x] Creator, image and alt can be overridden for each page
```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@site_account">
<meta name="twitter:creator" content="@individual_account">
<meta name="twitter:title" content="Content Title">
<meta name="twitter:description" content="Content description less than 200 characters">
<meta name="twitter:image" content="https://example.com/image.jpg">
<meta name="twitter:image:alt" content="Image alt text">
```
- [x] Website is claimed on Pinterest
```html
<meta name="p:domain_verify" content="verification-number"/>
```
